# Generated by Django 3.1.4 on 2020-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_date', models.DateTimeField(auto_now=True)),
                ('blog_text', models.TextField()),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
