# Generated by Django 3.1.4 on 2020-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201212_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_date',
            field=models.DateTimeField(),
        ),
    ]
